### ISSUE TITLE
This App is blocked

### ISSUE THREAD

**Issue by SComTheB** [google/google-analytics-utilities#13]
Hi everyone,

we have followed the instructions, but we cannot authorize the App/scripts within the sheet.

Message translated to English: This App has been blocked. The App tried to access confidential information.
![image](https://github.com/google/google-analytics-utilities/assets/137385674/d9cd509d-9e91-47c2-8026-2f783ad7979d)

Where can we unblock the script?
Which permissions should the account have, which is used running the scripts of the sheet?

Regards,
Björn

**Comment by SComTheB** [comment]
Just an update: We have now moved the sheet from a common Google Account with GA permissions to an existing Google Workspace account without GA permissions (yet) and I guess, we could now authorize the sheet. As the script asks for very, very broad permissions we are currently plan to move it to a completely new account.

**Comment by b-kuehn** [comment]
The "blocked" status is due to restrictions on what scripts you can run based on your Google Workspace settings. It sounds like you found a workaround, which is great!

I'll look into narrowing the permissions for the script so it isn't as concerning. All of the code in the script can be inspected and is not obfuscated in any way. I try to be as transparent with what the script does on as possible.
