### ISSUE TITLE
Boolean validation fields return errors in the functions when you use Sheet in a language that is not English

### ISSUE THREAD

**Issue by matteoboscolo** [google/google-analytics-utilities#5]
Boolean fields gets converted to language locale (i.e. if you use Sheet while your Google account is set to Italian, TRUE is VERO). Hence, they return errors in the functions. Switching Google account language to English solves the issue.

**Comment by b-kuehn** [comment]
Thanks for letting me know about this. I'm going to try and switch as many boolean columns to checkboxes in the spreadsheet to try and avoid this language issue. In the meantime, you should be able to add checkboxes to any sheet you might be using in place of "TRUE" or "FALSE" so that you don't have to change your account language. Please let me know if you run into any issues with this workaround.
